{"name": "Проверка ошибки получения заказов неавторизованного юзера", "status": "passed", "start": 1699698198210, "stop": 1699698199633, "uuid": "4eb1962d-66c2-4122-9a84-9bfa59fc3f0c", "historyId": "13fb01e33990dc1ade6a33066bf23274", "testCaseId": "13fb01e33990dc1ade6a33066bf23274", "fullName": "tests.test_get_orders_by_user.TestGetOrdersByUser#test_get_orders_unauthorized_user_failed_getting", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_orders_by_user"}, {"name": "subSuite", "value": "TestGetOrdersByUser"}, {"name": "host", "value": "MacBook-Pro-Evgeniya.local"}, {"name": "thread", "value": "1915-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_orders_by_user"}]}